server.address=0.0.0.0
server.port=3000

spring.application.name=dsmt
spring.datasource.url=jdbc:mysql://localhost:3306/dsmt
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

agario.supervisor-ip=25.10.61.231
agario.supervisor-port=49153

logging.level.org.springframework.security=DEBUG