server.address=0.0.0.0
server.port=3000
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=agario
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myapp

spring.application.name=dsmt
spring.datasource.url=jdbc:mysql://10.2.1.12:3306/dsmt
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

erlang-supervisor-connection.self-mb=springboot_mbox
erlang-supervisor-connection.self-node=springboot_node
erlang-supervisor-connection.self-erlang-ip=10.2.1.13
erlang-supervisor-connection.supervisor-cookie=mycookie

logging.level.org.springframework.security=DEBUG